# === Dataset ===
dataset: "cifar10"

# === Cellular automata parameters ===
n_channel : 16 
fire_rate: 0.1
hidden_channels: 128

experiment_map:
  Growing: 0
  Persistent: 1
  Regenerating: 2

#=== Training parameters ===
batch_size: 8
epochs: 10000 
n_steps: 128 #[64-96]
lr: 0.001
lr_gamma: 0.999

#=== Pattern Pool parameters ===
pool_size: 1024
experiment_type: "Persistent"

use_pattern_pool: true
damage_n: 0

#=== Checkpoint ===
checkpoint_path: "checkpoints/NCAModel_p.pt"

